# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  daily_idea_digest:
    class: IdeaDigestJob
    args:
      period: daily
    schedule: at 7am every day

  weekly_idea_digest:
    class: IdeaDigestJob
    args:
      period: weekly
    schedule: at 8am on Monday

  scheduled_backup:
    class: ScheduledBackupJob
    schedule: at 2am every day
